
-- 1. TB_TUTOR - o dono do animal
CREATE TABLE TB_TUTOR (
    ID_TUTOR   NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY
                               (START WITH 1 INCREMENT BY 1),
    NM_TUTOR   NVARCHAR2(100)  NOT NULL,
    CPF        NVARCHAR2(14)   NOT NULL,
    EMAIL      NVARCHAR2(100)  NOT NULL,
    TELEFONE   NVARCHAR2(20)   NOT NULL,
    ENDERECO   NVARCHAR2(200)  NOT NULL,
    CONSTRAINT PK_TB_TUTOR PRIMARY KEY (ID_TUTOR)
);

COMMENT ON TABLE  TB_TUTOR            IS 'Tutores responsaveis pelos pets. Entidade raiz do cadastro: um tutor pode ter varios pets.';
COMMENT ON COLUMN TB_TUTOR.ID_TUTOR   IS 'Identificador unico do tutor. Chave primaria gerada por IDENTITY.';
COMMENT ON COLUMN TB_TUTOR.NM_TUTOR   IS 'Nome completo do tutor.';
COMMENT ON COLUMN TB_TUTOR.CPF        IS 'CPF do tutor no formato 000.000.000-00. Unico: nao pode haver dois tutores com o mesmo CPF.';
COMMENT ON COLUMN TB_TUTOR.EMAIL      IS 'E-mail de contato. Unico: usado como canal de aviso de vacina vencendo.';
COMMENT ON COLUMN TB_TUTOR.TELEFONE   IS 'Telefone de contato com DDD.';
COMMENT ON COLUMN TB_TUTOR.ENDERECO   IS 'Endereco residencial do tutor.';

CREATE UNIQUE INDEX IX_TB_TUTOR_CPF   ON TB_TUTOR (CPF);
CREATE UNIQUE INDEX IX_TB_TUTOR_EMAIL ON TB_TUTOR (EMAIL);


-- 2. TB_CLINICA - a clinica veterinaria que realiza o atendimento
CREATE TABLE TB_CLINICA (
    ID_CLINICA   NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY
                                 (START WITH 1 INCREMENT BY 1),
    NM_CLINICA   NVARCHAR2(150)  NOT NULL,
    CNPJ         NVARCHAR2(18)   NOT NULL,
    ENDERECO     NVARCHAR2(200)  NOT NULL,
    TELEFONE     NVARCHAR2(20)   NOT NULL,
    EMAIL        NVARCHAR2(100)  NOT NULL,
    CONSTRAINT PK_TB_CLINICA PRIMARY KEY (ID_CLINICA)
);

COMMENT ON TABLE  TB_CLINICA              IS 'Clinicas veterinarias da rede. Cada consulta e sempre realizada em uma clinica.';
COMMENT ON COLUMN TB_CLINICA.ID_CLINICA   IS 'Identificador unico da clinica. Chave primaria gerada por IDENTITY.';
COMMENT ON COLUMN TB_CLINICA.NM_CLINICA   IS 'Nome fantasia da clinica, incluindo a unidade.';
COMMENT ON COLUMN TB_CLINICA.CNPJ         IS 'CNPJ no formato 00.000.000/0000-00. Unico por clinica.';
COMMENT ON COLUMN TB_CLINICA.ENDERECO     IS 'Endereco completo da unidade.';
COMMENT ON COLUMN TB_CLINICA.TELEFONE     IS 'Telefone comercial com DDD.';
COMMENT ON COLUMN TB_CLINICA.EMAIL        IS 'E-mail institucional da unidade.';

CREATE UNIQUE INDEX IX_TB_CLINICA_CNPJ ON TB_CLINICA (CNPJ);


-- 3. TB_PET - o animal, centro do dominio
CREATE TABLE TB_PET (
    ID_PET          NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY
                                    (START WITH 1 INCREMENT BY 1),
    NM_PET          NVARCHAR2(100)  NOT NULL,
    ESPECIE         NVARCHAR2(50)   NOT NULL,
    RACA            NVARCHAR2(100)  NOT NULL,
    DT_NASCIMENTO   TIMESTAMP(7)        NULL,
    PESO            NUMBER(6,2)         NULL,
    ID_TUTOR        NUMBER(10)      NOT NULL,
    CONSTRAINT PK_TB_PET PRIMARY KEY (ID_PET),
    
    CONSTRAINT FK_TB_PET_TB_TUTOR_ID_TUTOR
        FOREIGN KEY (ID_TUTOR) REFERENCES TB_TUTOR (ID_TUTOR)
);

COMMENT ON TABLE  TB_PET                 IS 'Animais cadastrados. Tabela central: consultas, vacinas e medicamentos se ligam a ela.';
COMMENT ON COLUMN TB_PET.ID_PET          IS 'Identificador unico do pet. Chave primaria gerada por IDENTITY.';
COMMENT ON COLUMN TB_PET.NM_PET          IS 'Nome do animal.';
COMMENT ON COLUMN TB_PET.ESPECIE         IS 'Especie do animal. Exemplos: Cachorro, Gato.';
COMMENT ON COLUMN TB_PET.RACA            IS 'Raca do animal.';
COMMENT ON COLUMN TB_PET.DT_NASCIMENTO   IS 'Data de nascimento. Opcional: nem todo tutor sabe a data exata em caso de adocao.';
COMMENT ON COLUMN TB_PET.PESO            IS 'Peso em quilogramas, com duas casas decimais. Usado para calculo de dosagem.';
COMMENT ON COLUMN TB_PET.ID_TUTOR        IS 'FK para TB_TUTOR. Indica de quem e o animal.';

CREATE INDEX IX_TB_PET_ID_TUTOR ON TB_PET (ID_TUTOR);


-- 4. TB_CONSULTA - o atendimento veterinario
CREATE TABLE TB_CONSULTA (
    ID_CONSULTA   NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY
                                  (START WITH 1 INCREMENT BY 1),
    DT_CONSULTA   TIMESTAMP(7)    NOT NULL,
    DESCRICAO     NVARCHAR2(500)  NOT NULL,
    DIAGNOSTICO   NVARCHAR2(500)  NOT NULL,
    ID_PET        NUMBER(10)      NOT NULL,
    ID_CLINICA    NUMBER(10)      NOT NULL,
    CONSTRAINT PK_TB_CONSULTA PRIMARY KEY (ID_CONSULTA),
    CONSTRAINT FK_TB_CONSULTA_TB_PET_ID_PET
        FOREIGN KEY (ID_PET) REFERENCES TB_PET (ID_PET) ON DELETE CASCADE,
    CONSTRAINT FK_TB_CONSULTA_TB_CLINICA_ID_CLINICA
        FOREIGN KEY (ID_CLINICA) REFERENCES TB_CLINICA (ID_CLINICA)
);

COMMENT ON TABLE  TB_CONSULTA               IS 'Consultas veterinarias. Liga o pet a clinica que o atendeu e registra o diagnostico.';
COMMENT ON COLUMN TB_CONSULTA.ID_CONSULTA   IS 'Identificador unico da consulta. Chave primaria gerada por IDENTITY.';
COMMENT ON COLUMN TB_CONSULTA.DT_CONSULTA   IS 'Data e hora em que o atendimento aconteceu.';
COMMENT ON COLUMN TB_CONSULTA.DESCRICAO     IS 'Motivo do atendimento e queixa relatada pelo tutor.';
COMMENT ON COLUMN TB_CONSULTA.DIAGNOSTICO   IS 'Diagnostico e conduta definidos pelo veterinario.';
COMMENT ON COLUMN TB_CONSULTA.ID_PET        IS 'FK para TB_PET. Animal atendido.';
COMMENT ON COLUMN TB_CONSULTA.ID_CLINICA    IS 'FK para TB_CLINICA. Unidade onde ocorreu o atendimento.';

CREATE INDEX IX_TB_CONSULTA_ID_PET     ON TB_CONSULTA (ID_PET);
CREATE INDEX IX_TB_CONSULTA_ID_CLINICA ON TB_CONSULTA (ID_CLINICA);



-- 5. TB_VACINA - carteirinha de vacinacao do pet

CREATE TABLE TB_VACINA (
    ID_VACINA         NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY
                                      (START WITH 1 INCREMENT BY 1),
    NM_VACINA         NVARCHAR2(100)  NOT NULL,
    FABRICANTE        NVARCHAR2(100)      NULL,
    DT_APLICACAO      TIMESTAMP(7)    NOT NULL,
    DT_PROXIMA_DOSE   TIMESTAMP(7)        NULL,
    ID_PET            NUMBER(10)      NOT NULL,
    ID_CONSULTA       NUMBER(10)          NULL,
    CONSTRAINT PK_TB_VACINA PRIMARY KEY (ID_VACINA),
    CONSTRAINT FK_TB_VACINA_TB_PET_ID_PET
        FOREIGN KEY (ID_PET) REFERENCES TB_PET (ID_PET) ON DELETE CASCADE,
    
    CONSTRAINT FK_TB_VACINA_TB_CONSULTA_ID_CONSULTA
        FOREIGN KEY (ID_CONSULTA) REFERENCES TB_CONSULTA (ID_CONSULTA)
);

COMMENT ON TABLE  TB_VACINA                   IS 'Vacinas aplicadas no pet. Resolve a dor central do projeto: a carteirinha de vacinacao perdida.';
COMMENT ON COLUMN TB_VACINA.ID_VACINA         IS 'Identificador unico do registro de vacina. Chave primaria gerada por IDENTITY.';
COMMENT ON COLUMN TB_VACINA.NM_VACINA         IS 'Nome da vacina aplicada. Exemplo: V10 (Polivalente Canina).';
COMMENT ON COLUMN TB_VACINA.FABRICANTE        IS 'Laboratorio fabricante. Opcional em registros historicos importados.';
COMMENT ON COLUMN TB_VACINA.DT_APLICACAO      IS 'Data em que a dose foi aplicada.';
COMMENT ON COLUMN TB_VACINA.DT_PROXIMA_DOSE   IS 'Data prevista do reforco. Base para o alerta automatico ao tutor.';
COMMENT ON COLUMN TB_VACINA.ID_PET            IS 'FK para TB_PET. Animal vacinado.';
COMMENT ON COLUMN TB_VACINA.ID_CONSULTA       IS 'FK opcional para TB_CONSULTA. Consulta em que a dose foi aplicada, quando houver.';

CREATE INDEX IX_TB_VACINA_ID_PET      ON TB_VACINA (ID_PET);
CREATE INDEX IX_TB_VACINA_ID_CONSULTA ON TB_VACINA (ID_CONSULTA);



-- 6. TB_MEDICAMENTO - tratamentos prescritos ao pet

CREATE TABLE TB_MEDICAMENTO (
    ID_MEDICAMENTO   NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY
                                     (START WITH 1 INCREMENT BY 1),
    NM_MEDICAMENTO   NVARCHAR2(100)  NOT NULL,
    DOSAGEM          NVARCHAR2(50)   NOT NULL,
    FREQUENCIA       NVARCHAR2(100)  NOT NULL,
    DT_INICIO        TIMESTAMP(7)    NOT NULL,
    DT_FIM           TIMESTAMP(7)        NULL,
    ID_PET           NUMBER(10)      NOT NULL,
    ID_CONSULTA      NUMBER(10)          NULL,
    CONSTRAINT PK_TB_MEDICAMENTO PRIMARY KEY (ID_MEDICAMENTO),
    CONSTRAINT FK_TB_MEDICAMENTO_TB_PET_ID_PET
        FOREIGN KEY (ID_PET) REFERENCES TB_PET (ID_PET) ON DELETE CASCADE,
    CONSTRAINT FK_TB_MEDICAMENTO_TB_CONSULTA_ID_CONSULTA
        FOREIGN KEY (ID_CONSULTA) REFERENCES TB_CONSULTA (ID_CONSULTA)
);

COMMENT ON TABLE  TB_MEDICAMENTO                  IS 'Medicamentos prescritos ao pet. Permite ao veterinario ver tratamentos em curso e evitar conflito medicamentoso.';
COMMENT ON COLUMN TB_MEDICAMENTO.ID_MEDICAMENTO   IS 'Identificador unico da prescricao. Chave primaria gerada por IDENTITY.';
COMMENT ON COLUMN TB_MEDICAMENTO.NM_MEDICAMENTO   IS 'Nome comercial do medicamento.';
COMMENT ON COLUMN TB_MEDICAMENTO.DOSAGEM          IS 'Dosagem prescrita, geralmente relacionada ao peso do animal.';
COMMENT ON COLUMN TB_MEDICAMENTO.FREQUENCIA       IS 'Intervalo de administracao. Exemplo: a cada 24 horas, em jejum.';
COMMENT ON COLUMN TB_MEDICAMENTO.DT_INICIO        IS 'Data de inicio do tratamento.';
COMMENT ON COLUMN TB_MEDICAMENTO.DT_FIM           IS 'Data de termino. Nulo enquanto o tratamento for continuo.';
COMMENT ON COLUMN TB_MEDICAMENTO.ID_PET           IS 'FK para TB_PET. Animal em tratamento.';
COMMENT ON COLUMN TB_MEDICAMENTO.ID_CONSULTA      IS 'FK opcional para TB_CONSULTA. Consulta em que houve a prescricao.';

CREATE INDEX IX_TB_MEDICAMENTO_ID_PET      ON TB_MEDICAMENTO (ID_PET);
CREATE INDEX IX_TB_MEDICAMENTO_ID_CONSULTA ON TB_MEDICAMENTO (ID_CONSULTA);



CREATE TABLE TB_USUARIO_PETCARE (
    ID_USUARIO   NUMBER(10)      GENERATED BY DEFAULT ON NULL AS IDENTITY
                                 (START WITH 1 INCREMENT BY 1),
    NM_USUARIO   NVARCHAR2(100)  NOT NULL,
    EMAIL        NVARCHAR2(100)  NOT NULL,
    SENHA_HASH   NVARCHAR2(256)  NOT NULL,
    PERFIL       NVARCHAR2(20)   NOT NULL,
    DT_CRIACAO   TIMESTAMP(7)    NOT NULL,
    CONSTRAINT PK_TB_USUARIO_PETCARE PRIMARY KEY (ID_USUARIO)
);

COMMENT ON TABLE  TB_USUARIO_PETCARE             IS 'Usuarios que acessam a API. A senha nunca e gravada em texto puro, apenas o hash PBKDF2 com salt.';
COMMENT ON COLUMN TB_USUARIO_PETCARE.ID_USUARIO  IS 'Identificador unico do usuario. Chave primaria gerada por IDENTITY.';
COMMENT ON COLUMN TB_USUARIO_PETCARE.NM_USUARIO  IS 'Nome de exibicao do usuario.';
COMMENT ON COLUMN TB_USUARIO_PETCARE.EMAIL       IS 'E-mail usado no login. Unico por usuario.';
COMMENT ON COLUMN TB_USUARIO_PETCARE.SENHA_HASH  IS 'Hash PBKDF2-SHA256 da senha, no formato iteracoes.salt.hash.';
COMMENT ON COLUMN TB_USUARIO_PETCARE.PERFIL      IS 'Perfil de acesso usado na autorizacao: Admin ou Usuario.';
COMMENT ON COLUMN TB_USUARIO_PETCARE.DT_CRIACAO  IS 'Data e hora (UTC) de criacao do usuario.';

CREATE UNIQUE INDEX IX_TB_USUARIO_PETCARE_EMAIL ON TB_USUARIO_PETCARE (EMAIL);




INSERT INTO TB_TUTOR (NM_TUTOR, CPF, EMAIL, TELEFONE, ENDERECO) VALUES
    ('Murillo Fernandes Carapia', '123.456.789-00', 'murillo@petcare360.com.br', '(11) 99999-0001', 'Av. Lins de Vasconcelos, 1222 - Cambuci, Sao Paulo/SP');
INSERT INTO TB_TUTOR (NM_TUTOR, CPF, EMAIL, TELEFONE, ENDERECO) VALUES
    ('Ana Beatriz Souza', '987.654.321-00', 'ana.souza@petcare360.com.br', '(11) 99999-0002', 'R. Augusta, 1500 - Consolacao, Sao Paulo/SP');

INSERT INTO TB_CLINICA (NM_CLINICA, CNPJ, ENDERECO, TELEFONE, EMAIL) VALUES
    ('CLYVO VET - Unidade Paulista', '12.345.678/0001-99', 'Av. Paulista, 1500 - Bela Vista, Sao Paulo/SP', '(11) 3000-1000', 'paulista@clyvovet.com.br');
INSERT INTO TB_CLINICA (NM_CLINICA, CNPJ, ENDERECO, TELEFONE, EMAIL) VALUES
    ('PetCare 360 - Unidade Vila Mariana', '98.765.432/0001-11', 'R. Domingos de Morais, 800 - Vila Mariana, Sao Paulo/SP', '(11) 3000-2000', 'vilamariana@petcare360.com.br');

INSERT INTO TB_PET (NM_PET, ESPECIE, RACA, DT_NASCIMENTO, PESO, ID_TUTOR) VALUES
    ('Rex', 'Cachorro', 'Labrador Retriever', TO_TIMESTAMP('2020-05-10', 'YYYY-MM-DD'), 28.50, 1);
INSERT INTO TB_PET (NM_PET, ESPECIE, RACA, DT_NASCIMENTO, PESO, ID_TUTOR) VALUES
    ('Mel', 'Gato', 'Siames', TO_TIMESTAMP('2022-08-03', 'YYYY-MM-DD'), 4.20, 2);

INSERT INTO TB_CONSULTA (DT_CONSULTA, DESCRICAO, DIAGNOSTICO, ID_PET, ID_CLINICA) VALUES
    (TO_TIMESTAMP('2026-03-12 09:30:00', 'YYYY-MM-DD HH24:MI:SS'), 'Consulta de rotina anual com aplicacao de vacina', 'Animal saudavel, peso adequado para a raca', 1, 1);
INSERT INTO TB_CONSULTA (DT_CONSULTA, DESCRICAO, DIAGNOSTICO, ID_PET, ID_CLINICA) VALUES
    (TO_TIMESTAMP('2026-04-02 14:00:00', 'YYYY-MM-DD HH24:MI:SS'), 'Retorno por episodios de vomito e apatia', 'Gastrite alimentar leve, tratamento medicamentoso por 7 dias', 2, 2);

INSERT INTO TB_VACINA (NM_VACINA, FABRICANTE, DT_APLICACAO, DT_PROXIMA_DOSE, ID_PET, ID_CONSULTA) VALUES
    ('V10 (Polivalente Canina)', 'Zoetis', TO_TIMESTAMP('2026-03-12', 'YYYY-MM-DD'), TO_TIMESTAMP('2027-03-12', 'YYYY-MM-DD'), 1, 1);
INSERT INTO TB_VACINA (NM_VACINA, FABRICANTE, DT_APLICACAO, DT_PROXIMA_DOSE, ID_PET, ID_CONSULTA) VALUES
    ('Antirrabica Felina', 'MSD Saude Animal', TO_TIMESTAMP('2026-04-02', 'YYYY-MM-DD'), TO_TIMESTAMP('2027-04-02', 'YYYY-MM-DD'), 2, 2);

INSERT INTO TB_MEDICAMENTO (NM_MEDICAMENTO, DOSAGEM, FREQUENCIA, DT_INICIO, DT_FIM, ID_PET, ID_CONSULTA) VALUES
    ('Vermifugo Drontal Plus', '1 comprimido para cada 10 kg', 'Dose unica, repetir em 15 dias', TO_TIMESTAMP('2026-03-12', 'YYYY-MM-DD'), TO_TIMESTAMP('2026-03-27', 'YYYY-MM-DD'), 1, 1);
INSERT INTO TB_MEDICAMENTO (NM_MEDICAMENTO, DOSAGEM, FREQUENCIA, DT_INICIO, DT_FIM, ID_PET, ID_CONSULTA) VALUES
    ('Omeprazol 10mg', '1 comprimido ao dia', 'A cada 24 horas, em jejum', TO_TIMESTAMP('2026-04-02', 'YYYY-MM-DD'), TO_TIMESTAMP('2026-04-09', 'YYYY-MM-DD'), 2, 2);

COMMIT;